name: batch2ui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_rating_stars: ^1.1.0
  flutter_randomcolor: ^1.0.16
  flutter_screenutil: ^5.9.3
  flame: ^1.23.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter section for assets and fonts
flutter:
  uses-material-design: true

  # Add image assets
  assets:
    - assets/ic_launcher.png
    - assets/logo.jpeg
    - assets/usman.jpg
    - assets/university.jpeg
    - assets/shirt3.png
    - assets/shirt2.jpg
    - assets/shirt1.jpg
    - assets/security.png
    - assets/plant.jpg
    - assets/plant2.jpg
    - assets/logo2.png
    - assets/usman2.png
    - assets/profile.png

  # Add custom fonts
  fonts:
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf
